apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    app: my-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx
      volumeMounts:
        - name: mystorage
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: mystorage
      persistentVolumeClaim:
        claimName: pvc